### ISSUE TITLE
关于对象初始化的小建议？

### ISSUE THREAD

**Issue by oit63** [qddnovo/LinkBlock#2]
你好，我有一些建议

现在 LinkBlock是这样
UIButton \* button;
button = [[UIButton alloc] init];
button.viewAddToView(self.view);
我认为下面这样可能会要更方便一些
UIButton \* button;
button.viewAddToView(self.view);
button 如果不存在，会先调用默认的 new 方法

或者也可以这样
UIButton \* button;
button.new( ).viewAddToView(self.view);

**Comment by beforeold** [comment]
button is nil, so it can not receive any message, you can use the #define UIButtonNew to get a new button.
