### ISSUE TITLE
另外有个 Bug 关于 viewBGColorRandom

### ISSUE THREAD

**Issue by oit63** [qddnovo/LinkBlock#3]
viewBGColorRandom 后面 跟链式语法会报错，例如
 lable.viewBGColorRandom.viewAddToView(self.view);

错误是

 Member reference base type 'UIView *(^)()' is not a structure or union

**Comment by oit63** [comment]
看了下源码，
发现应该是 lable.viewBGColorRandom().viewAddToView(self.view);
= =, 忘了加括号了，用Block的时候 编译器没有提示。。。还有点不太习惯。。

**Comment by AAdonis** [comment]
赞赞赞赞赞赞赞赞赞赞赞赞

**Comment by Meterwhite** [comment]
谢谢关注
