### ISSUE TITLE
消除Warnings

### ISSUE THREAD

**Issue by oit63** [qddnovo/LinkBlock#5]
兄弟，你看能不能把这几个Warning 消一下，因为你库里的podspec 没更新，pod install 不了，inhibit_all_warnings! 就用不了,所以只能麻烦你消一下了。

./LinkBlock/UIKit/UITextField+LinkBlock.h:11:21: Duplicate definition of category 'UIViewControllerLinkBlock' on interface 'NSObject'

./LinkBlock/Foundation/NSDate+LinkBlock.m:12:17: Property 'dateCurrentZone' requires method 'setDateCurrentZone:' to be defined - use @dynamic or provide a method implementation in this category

./LinkBlock/UIKit/UIViewController+LinkBlock.m:12:17: Property 'txtFieldPlaceholdColor' requires method 'txtFieldPlaceholdColor' to be defined - use @dynamic or provide a method implementation in this category

./LinkBlock/UIKit/UIViewController+LinkBlock.m:12:17: Property 'txtFieldPlaceholdColor' requires method 'setTxtFieldPlaceholdColor:' to be defined - use @dynamic or provide a method implementation in this category

./LinkBlock/Foundation/NSMutableArray+LinkBlock.m:351:1: Conflicting return type in implementation of 'm_arrObjsOfType': 'NSArray *(^)(__unsafe_unretained Class)' vs 'NSMutableArray *(^)(__unsafe_unretained Class)'

./LinkBlock/UIKit/UIViewController+LinkBlock.h:12:21: Duplicate definition of category 'UIViewControllerLinkBlock' on interface 'NSObject'

./LinkBlock/Foundation/NSNumber+LinkBlock.m:12:17: Property 'numSetHeightToViews' requires method 'numSetHeightToViews' to be defined - use @dynamic or provide a method implementation in this category

./LinkBlock/Foundation/NSNumber+LinkBlock.m:12:17: Property 'numSetHeightToViews' requires method 'setNumSetHeightToViews:' to be defined - use @dynamic or provide a method implementation in this category

**Comment by Meterwhite** [comment]
你好，已经提交到cocoapods。谢谢支持。
