### ISSUE TITLE
NSString 的 append方法 

### ISSUE THREAD

**Issue by oit63** [qddnovo/LinkBlock#7]
strAppend()比较好用, 但是只要后面的字符串为空就抛出异常了, 这样有时候不是很好用, 建议可以提供一个宏选择关闭抛出这种异常

**Comment by Meterwhite** [comment]
取值时，针对链条中发生的异常，设计了end()方法来在链条结尾处获取处理异常后的值。不知道是否可以使用这个方法解决这种情况呢，谢谢。

**Comment by oit63** [comment]
好的
